### PR TITLE
Added Emma.

### PR DESCRIPTION
**Pull request by niffer01**
I've added Emma to the project, but it fails to create the coverage report.  Everything else still works, however.

Here's the issue I'm having: The JVM isn't creating the file coverage.ec as it is running the tests.  Without this file Emma cannot generate the coverage report.  It looks like the coverage.out.file property isn't getting set even though I'm setting it in the script - that is the property that tells the JVM the name of the file.  It has to use an absolute path, which it is using, to prevent the JVM from dumping the file wherever.  But I even did a search for the file on my entire hard drive and still no luck.

I did a lot of Googling on this and didn't find anything to fix the problem, but I did find notes that Emma doesn't work with Java 7 and beyond.  I am using Java 8, so I think getting a coverage report on my computer is a lost cause.  However, you guys might have better luck so that is why I am making the pull request.  As I said, this won't break anything, it just isn't doing what we want it to do, namely create the coverage report.

Emma Overview:

The lib directory has two new files, emma.jar and emma_ant.jar.  This is all you need installed for you to use Emma.  The build.xml file has been adjusted so that every time you run ant it will kick off Emma.  (You can write it so you can run Emma or not, but for simplicity's sake I have it running Emma all the time.)  The script will create an emma directory which will have the coverage reports and Emma data files.  The script also creates emmainstr under the build directory.  This will have the compiled code.  It's copied from the build\classes directory.  I had to set Emma to copy all of the files to include the interfaces (mode="fullcopy").  Without that setting Emma would copy only the active classes, and things failed without the interfaces.

The Emma directories look like this:

have-no-bananas
  build
    classes
    emmainstr
    report
  emma
    <emma files>
  lib
    emma.jar
    emma_ant.jar
    <all the other .jars>

Tomorrow (Friday) I will start working with Cobertura, although I also saw similar comments on the web about that being unstable with the new Java version.  A few people recommended JaCoCo, which was written by former Emma for Eclipse developers, so I may resort to that.  I'm hoping, however, that Emma will work for you guys and I'm just the oddball.

### CODE REVIEW

**Comment by niffer01** [comment]
I should have previewed this first.  The formatting for the file directories got messed up because HTML ignores double spaces.  Here's a better version:

The Emma directories look like this:

have-no-bananas
--build
----classes
----emmainstr
----report
--emma
----emma data files
--lib
----emma.jar
----emma_ant.jar

**Comment by smarks** [comment]
Hi,

I just did a git clone of your repo and typed:

ant test

but the code did not compile.

> ant test
> Buildfile: 
> /Users/spencermarks/local-dev/uml/summer14/have-no-bananas/build.xml

clean:

init:
     [mkdir] Created dir: 
/Users/spencermarks/local-dev/uml/summer14/have-no-bananas/build
     [mkdir] Created dir: 
/Users/spencermarks/local-dev/uml/summer14/have-no-bananas/build/classes
     [mkdir] Created dir: 
/Users/spencermarks/local-dev/uml/summer14/have-no-bananas/build/report

compile:
     [javac] 
/Users/spencermarks/local-dev/uml/summer14/have-no-bananas/build.xml:88: 
warning: 'includeantruntime' was not set, defaulting to 
build.sysclasspath=last; set to false for repeatable builds
     [javac] Compiling 28 source files to 
/Users/spencermarks/local-dev/uml/summer14/have-no-bananas/build/classes
     [javac] 
/Users/spencermarks/local-dev/uml/summer14/have-no-bananas/src/test/java/bananas/shoppingListDAOTest.java:14: 
error: package main.java.bananas does not exist
     [javac] import main.java.bananas.DAOException;
     [javac]                         ^
     [javac] 
/Users/spencermarks/local-dev/uml/summer14/have-no-bananas/src/test/java/bananas/shoppingListDAOTest.java:15: 
error: package main.java.bananas does not exist
     [javac] import main.java.bananas.DAOUtils;
     [javac]                         ^
     [javac] 
/Users/spencermarks/local-dev/uml/summer14/have-no-bananas/src/test/java/bananas/shoppingListDAOTest.java:16: 
error: package main.java.bananas does not exist
     [javac] import main.java.bananas.FoodItem;
     [javac]                         ^
     [javac] 
/Users/spencermarks/local-dev/uml/summer14/have-no-bananas/src/test/java/bananas/shoppingListDAOTest.java:17: 
error: package main.java.bananas does not exist
     [javac] import main.java.bananas.ListItem;
     [javac]                         ^
     [javac] 
/Users/spencermarks/local-dev/uml/summer14/have-no-bananas/src/test/java/bananas/shoppingListDAOTest.java:18: 
error: package main.java.bananas does not exist
     [javac] import main.java.bananas.ListOfItems;
     [javac]                         ^
     [javac] 
/Users/spencermarks/local-dev/uml/summer14/have-no-bananas/src/test/java/bananas/shoppingListDAOTest.java:19: 
error: package main.java.bananas does not exist
     [javac] import main.java.bananas.ShoppingList;
     [javac]                         ^
     [javac] 
/Users/spencermarks/local-dev/uml/summer14/have-no-bananas/src/test/java/bananas/shoppingListDAOTest.java:20: 
error: package main.java.bananas does not exist
     [javac] import main.java.bananas.ShoppingListDAO;
     [javac]                         ^
     [javac] Note: Some input files use unchecked or unsafe operations.
     [javac] Note: Recompile with -Xlint:unchecked for details.
     [javac] 7 errors

BUILD FAILED
/Users/spencermarks/local-dev/uml/summer14/have-no-bananas/build.xml:88: 
Compile failed; see the compiler error output for details.

Total time: 1 second

Spencer

**Comment by niffer01** [comment]
Aaagh!  I thought those import statements had been removed.  I may have
clobbered my version of code since I had to revert back a few versions
before I could rebase.  I made the mistake of committing my Emma work as I
went along so I got error messages when I tried to rebase.  Oddly, the
build worked when I tested it before doing the pull request.  Maybe
something got skipped in the push.

I'll fix it tonight when I get home.

Jen

**Comment by smarks** [comment]
OK, sounds good. I'll check again when I see another email.

Spencer

**Comment by bthet4d** [comment]
I just reread and saw the java 7 and beyond. Missed that, but I added the
emma.jar and emma_ant.jar. I do not see any coverage reports. There was
a directory named "emma" added with the file "metadat.em", but no coverage
reports. I also notice that the lib folder in emmainstr was empty.

**Comment by niffer01** [comment]
I think it's ok for the emmainstr\lib folder to be empty.

I just fixed ShoppingListDAOTest.java in my repo.  It doesn't have the
stray import statements anymore.

Jen

**Comment by bthet4d** [comment]
I think the master is up to date import wise. I'll check. How did the other
coverage tool work out?

**Comment by niffer01** [comment]
I got the build.xml working with Cobertura.  However, it isn't reporting
any coverage.  I'll troubleshoot tomorrow.  On the plus side Cobertura
provided a better example build.xml that I could use to integrate with the
current build.xml.

**Comment by tinsweep** [comment]
Thanks for working so much on this, Cobertura's site looks much more
informative and understandable than Emma's

**Comment by smarks** [comment]
Hi

The build is looking better. I was able to checkout and ant test 
reported success with 42 tests. Nice work. Have you been using IDEA's 
code coverage at all?

Spencer

**Comment by niffer01** [comment]
I haven't been able to use IDEA's code coverage with this project.  My
files are installed in GitHub's directory, and for some reason IDEA can't
handle them there.  The test classes can't see the main classes when I run
the project in IDEA from the GitHub directory.  So, instead of running
things in IDEA I just run the ant script.

Jen

**Comment by niffer01** [comment]
I just added Cobertura stuff to the pull request so you guys can play with both Emma and Cobertura.  If one of them works for you let me know.  The current build.xml is set for Cobertura, but I added a copy of it called build_with_cobertura.xml.  That way you can switch back and forth between the two by changing the file name.

In the meantime I'll try to figure out why Cobertura isn't covering any classes for me.

**Comment by smarks** [comment]
Yes, the cobertura reports and the coverage numbers look great - nice 
work.

Spencer

**Comment by bthet4d** [comment]
Everything here looks good to me. I am fine with this being merged.

Sent via the Samsung Galaxy S™ III, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by tinsweep** [comment]
Looks good here too. Merge away!

**Pull request merged**
