### PR TITLE
Branch for comments sam

### PR DESCRIPTION
**Pull request by smarks**
Hi, 
I created a branch from master in order to write some comments, but I am not finding a lot of code here. Do you have the right project? If some, I'd expect to see more work here. Don't work on branches too long otherwise others can't use your work.

### CODE REVIEW

**Comment by smarks** [comment]
Please let me know what's going on - thanks.

**Comment by niffer01** [comment]
I pushed some changes to my pull request this weekend, or at least I
thought I did.  Let me know if you don't see the changes and I'll close the
pull request and start a fresh one.

The main change was I added equals() and hashCode() to ShoppingList.

Jen

**Comment by smarks** [comment]
I have just been looking at what's in master. 

Spencer

**Comment by bthet4d** [comment]
I'm replying from the hip here, without having looked at our repos in the context of this issue,  but would guess the situation is due to a few unmerged pull requests. We are working off of forks of Andrew's repo and I know he has been really busy the past week or two.

Sent via the Samsung Galaxy S™ III, an AT&T 4G LTE smartphone

-------- Original message --------

**Pull request closed without merging**
